<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>LoeBalance.Platform.Windows</AssemblyName>
    <RootNamespace>LoeBalance.Platform.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LoeBalance.Core\LoeBalance.Core.csproj" />
  </ItemGroup>
</Project>
