<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>LoeBalance.Desktop.Wpf</AssemblyName>
    <RootNamespace>LoeBalance.Desktop.Wpf</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LoeBalance.Core\LoeBalance.Core.csproj" />
    <ProjectReference Include="..\LoeBalance.Platform.Windows\LoeBalance.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
